version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: laravel-app
    container_name: laravel_app
    restart: unless-stopped
    environment:
      - APP_ENV=local
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=qrcode_db
      - DB_USERNAME=root
      - DB_PASSWORD=test
    volumes:
      - .:/var/www
    networks:
      - laravel
    depends_on:
      - db
  nginx:
    image: nginx:latest
    container_name: nginx_webserver
    ports:
      - "8000:80"
    volumes:
      - .:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
      - db
    networks:
      - laravel

  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: qrcode_db
      MYSQL_ROOT_PASSWORD: test
    networks:
      - laravel
    ports:
      - "3308:3306"

networks:
  laravel:
    driver: bridge
